# Generated by Django 5.2 on 2025-05-04 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_userdetails_delete_tech'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDetails',
        ),
    ]
