# Generated by Django 5.2 on 2025-05-04 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('website', '0003_delete_userdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('semester', models.IntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('hash_code', models.CharField(max_length=64, unique=True)),
            ],
        ),
    ]
