# Generated by Django 5.2 on 2025-05-04 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_aboutme'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='title',
            field=models.CharField(default='About Me', max_length=100),
        ),
    ]
