# Generated by Django 5.2 on 2025-05-04 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_aboutme_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='resume',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
